const books = [
    {
        cover: null,
        title: 'The Great Gatsby',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/the-great-gatsby',
        author_id: 1
    },
    {
        cover: null,
        title: 'Pride & Prejudice',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/pride-prejudice',
        author_id: 2
    },
    {
        cover: null,
        title: 'Romeo and Juliet',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/romeo-and-juliet',
        author_id: 3
    },
    {
        cover: null,
        title: 'Little Women',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/little-women',
        author_id: 4
    },
    {
        cover: null,
        title: 'Jane Eyre',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/jane-eyre',
        author_id: 5
    },
    {
        cover: null,
        title: 'Wuthering Heights',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/wuthering-heights',
        author_id: 6
    },
    {
        cover: null,
        title: 'Frankenstein',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/frankenstein',
        author_id: 7
    },
    {
        cover: null,
        title: 'The Picture of Dorian Gray',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/the-picture-of-dorian-gray',
        author_id: 8
    },
    {
        cover: null,
        title: 'The Adventures of Huckleberry Finn',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/the-adventures-of-huckleberry-finn',
        author_id: 9
    },
    {
        cover: null,
        title: 'Dracula',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/dracula',
        author_id: 10
    },
    {
        cover: null,
        title: 'The Odyssey',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/the-odyssey',
        author_id: 11
    },
    {
        cover: null,
        title: 'Anne of Green Gables',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/anne-of-green-gables',
        author_id: 12
    },
    {
        cover: null,
        title: 'A Tale of Two Cities',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/a-tale-of-two-cities',
        author_id: 13
    },
    {
        cover: null,
        title: 'The Count of Monte Cristo',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/the-count-of-monte-cristo',
        author_id: 14
    },
    {
        cover: null,
        title: 'Crime and Punishment',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/crime-and-punishment',
        author_id: 15
    },
    {
        cover: null,
        title: 'Emma',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/emma',
        author_id: 2
    },
    {
        cover: null,
        title: 'Anna Karenina',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/anna-karenina',
        author_id: 16
    },
    {
        cover: null,
        title: 'Les Misérables',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/ebooks/les-misérables',
        author_id: 17
    },
    {
        cover: null,
        title: "Alice's Adventures in Wonderland",
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/alice-s-adventures-in-wonderland',
        author_id: 18
    },
    {
        cover: null,
        title: 'Moby-Dick',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/moby-dick',
        author_id: 19
    },
    {
        cover: null,
        title: 'The Art of War',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/the-art-of-war',
        author_id: 20
    },
    {
        cover: null,
        title: 'The Wonderful Wizard of Oz',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/wizard-of-oz',
        author_id: 21
    },
    {
        cover: null,
        title: 'The Iliad',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/the-iliad',
        author_id: 11
    },
    {
        cover: null,
        title: 'The Adventures of Sherlock Holmes',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/the-adventures-of-sherlock-holmes',
        author_id: 22
    },
    {
        cover: null,
        title: 'The Call of the Wild',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/the-call-of-the-wild-novel-by-jack-london',
        author_id: 23
    },
    {
        cover: null,
        title: 'Peter Pan',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/peter-pan',
        author_id: 24
    },
    {
        cover: null,
        title: 'Meditations',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/meditations',
        author_id: 25
    },
    {
        cover: null,
        title: 'The Strange Case of Dr Jekyll and Mr Hyde',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/the-strange-case-of-dr-jekyll-and-mr-hyde',
        author_id: 26
    },
    {
        cover: null,
        title: "Le Morte d'Arthur",
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/le-morte-d-arthur',
        author_id: 27
    },
    {
        cover: null,
        title: 'The Autobiography of Benjamin Franklin',
        files: null,
        language: 'en',
        link: 'https://publicdomainlibrary.org/en/books/the-autobiography-of-benjamin-franklin',
        author_id: 28
    }

];

const authors = [
    {
        name: 'F. Scott Fitzgerald',
        image: 'test',
        birth: '1896-09-24',
        death: '1940-12-21',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/f-scott-fitzgerald'
    },
    {
        name: 'Jane Austen',
        image: null,
        birth: '1775-12-16',
        death: '1817-07-18',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/jane-austen'
    },
    {
        name: 'William Shakespeare',
        image: null,
        birth: null,
        death: '1616-04-23',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/william-shakespeare'
    },
    {
        name: 'Louisa May Alcott',
        image: null,
        birth: '1832-11-29',
        death: '1888-03-06',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/louisa-may-alcott'
    },
    {
        name: 'Charlotte Brontë',
        image: null,
        birth: '1816-04-21',
        death: '1855-03-31',
        description: null,
        link: 'https://publicdomainlibrary.org/en/books/jane-eyre'
    },
    {
        name: 'Emily Brontë',
        image: null,
        birth: '1818-06-30',
        death: '1848-12-19',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/emily-brontë'
    },
    {
        name: 'Mary Shelley',
        image: null,
        birth: '1797-08-30',
        death: '1851-02-01',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/mary-wollstonecraft-shelley'
    },
    {
        name: 'Oscar Wilde',
        image: null,
        birth: '1854-10-16',
        death: '1900-11-30',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/oscar-wilde'
    },
    {
        name: 'Mark Twain',
        image: null,
        birth: '1835-11-30',
        death: '1910-04-21',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/mark-twain'
    },
    {
        name: 'Bram Stoker',
        image: null,
        birth: '1847-11-08',
        death: '1912-04-20',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/bram-stoker'
    },
    {
        name: 'Homer',
        image: null,
        birth: null,
        death: null,
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/homer'
    },
    {
        name: 'L. M. Montgomery',
        image: null,
        birth: '1874-11-30',
        death: '1942-04-24',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/lucy-maud-montgomery'
    },
    {
        name: 'Charles Dickens',
        image: null,
        birth: '1812-02-07',
        death: '1870-06-09',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/charles-john-huffam-dickens'
    },
    {
        name: 'Alexandre Dumas',
        image: null,
        birth: '1802-07-24',
        death: '1870-12-05',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/alexandre-dumas'
    },
    {
        name: 'Fyodor Dostoevsky',
        image: null,
        birth: '1821-11-11',
        death: '1881-02-09',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/fyodor-dostoevsky'
    },
    {
        name: 'Leo Tolstoy',
        image: null,
        birth: '1828-09-09',
        death: '1910-11-20',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/leo-tolstoy'
    },
    {
        name: 'Victor Hugo',
        image: null,
        birth: '1802-02-26',
        death: '1885-05-22',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/victor-hugo'
    },
    {
        name: 'Lewis Carroll',
        image: null,
        birth: '1832-01-27',
        death: '1898-01-14',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/lewis-carroll'
    },
    {
        name: 'Herman Melville',
        image: null,
        birth: '1819-08-01',
        death: '1891-09-28',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/herman-melville'
    },
    {
        name: 'Sun Tzu',
        image: null,
        birth: null,
        death: null,
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/sun-tzu'
    },
    {
        name: 'L. Frank Baum',
        image: null,
        birth: '1856-05-15',
        death: '1919-05-06',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/l-frank-baum'
    },
    {
        name: 'Arthur Conan Doyle',
        image: null,
        birth: '1859-05-22',
        death: '1930-07-07',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/arthur-conan-doyle'
    },
    {
        name: 'Jack London',
        image: null,
        birth: '1876-01-12',
        death: '1916-11-22',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/jack-london'
    },
    {
        name: 'J. M. Barrie',
        image: null,
        birth: '1860-05-09',
        death: '1937-06-19',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/james-matthew-barrie'
    },
    {
        name: 'Marcus Aurelius',
        image: null,
        birth: '0121-04-26',
        death: '0180-03-17',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/marcus-aurelius'
    },
    {
        name: 'Robert Louis Stevenson',
        image: null,
        birth: '1850-11-13',
        death: '1894-12-03',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/robert-louis-stevenson'
    },
    {
        name: 'Sir Thomas Malory',
        image: null,
        birth: null,
        death: '1471-03-14',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/thomas-malory'
    },
    {
        name: 'Benjamin Franklin',
        image: null,
        birth: '1706-01-17',
        death: '1790-04-17',
        description: null,
        link: 'https://publicdomainlibrary.org/en/authors/benjamin-franklin'
    }
];

const quotes = [
    // 1 The Great Gatsby
    { book_id: 1, popularity: 12544, quote: "So we beat on, boats against the current, borne back ceaselessly into the past." },
    { book_id: 1, popularity: 10566, quote: "I hope she'll be a fool -- that's the best thing a girl can be in this world, a beautiful little fool." },
    { book_id: 1, popularity: 5463, quote: "Angry, and half in love with her, and tremendously sorry, I turned away." },
    { book_id: 1, popularity: 4803, quote: "I was within and without, simultaneously enchanted and repelled by the inexhaustible variety of life." },
    { book_id: 1, popularity: 4668, quote: "And I like large parties. They’re so intimate. At small parties there isn’t any privacy." },
    { book_id: 1, popularity: 4410, quote: "And so with the sunshine and the great bursts of leaves growing on the trees, just as things grow in fast movies, I had that familiar conviction that life was beginning over again with the summer." },
    { book_id: 1, popularity: 4020, quote: "I wasn’t actually in love, but I felt a sort of tender curiosity." },
    { book_id: 1, popularity: 4007, quote: "He smiled understandingly—much more than understandingly. It was one of those rare smiles with a quality of eternal reassurance in it, that you may come across four or five times in life. It faced—or seemed to face—the whole eternal world for an instant, and then concentrated on you with an irresistible prejudice in your favor. It understood you just as far as you wanted to be understood, believed in you as you would like to believe in yourself, and assured you that it had precisely the impression of you that, at your best, you hoped to convey." },
    { book_id: 1, popularity: 3890, quote: "Let us learn to show our friendship for a man when he is alive and not after he is dead." },
    { book_id: 1, popularity: 3181, quote: "You see I usually find myself among strangers because I drift here and there trying to forget the sad things that happened to me." },
    { book_id: 1, popularity: 3060, quote: "There are only the pursued, the pursuing, the busy and the tired." },
    { book_id: 1, popularity: 2909, quote: "In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever since. 'Whenever you feel like criticizing any one,' he told me, 'just remember that all the people in this world haven’t had the advantages that you’ve had.'" },
    { book_id: 1, popularity: 2743, quote: "Life starts all over again when it gets crisp in the fall." },
    // Pride & Prejudice
    { book_id: 2, popularity: 20378, quote: "I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library." },
    { book_id: 2, popularity: 17925, quote: "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment." },
    { book_id: 2, popularity: 7908, quote: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife." },
    { book_id: 2, popularity: 7812, quote: "There are few people whom I really love, and still fewer of whom I think well. The more I see of the world, the more am I dissatisfied with it; and every day confirms my belief of the inconsistency of all human characters, and of the little dependence that can be placed on the appearance of merit or sense." },
    { book_id: 2, popularity: 6995, quote: "I cannot fix on the hour, or the spot, or the look or the words, which laid the foundation. It is too long ago. I was in the middle before I knew that I had begun." },
    { book_id: 2, popularity: 6168, quote: "Angry people are not always wise." },
    { book_id: 2, popularity: 5482, quote: "Vanity and pride are different things, though the words are often used synonymously. A person may be proud without being vain. Pride relates more to our opinion of ourselves, vanity to what we would have others think of us." },
    { book_id: 2, popularity: 4997, quote: "What are men to rocks and mountains?" },
    { book_id: 2, popularity: 4918, quote: "There is a stubbornness about me that never can bear to be frightened at the will of others. My courage always rises at every attempt to intimidate me." },
    { book_id: 2, popularity: 4379, quote: "I could easily forgive his pride, if he had not mortified mine." },
    { book_id: 2, popularity: 3353, quote: "I must learn to be content with being happier than I deserve." },
    { book_id: 2, popularity: 2393, quote: "You are too generous to trifle with me. If your feelings are still what they were last April, tell me so at once. My affections and wishes are unchanged; but one word from you will silence me on this subject for ever." },
    { book_id: 2, popularity: 2217, quote: "I have not the pleasure of understanding you." },
    { book_id: 2, popularity: 2064, quote: "To be fond of dancing was a certain step towards falling in love." },
    { book_id: 2, popularity: 2048, quote: "I am the happiest creature in the world. Perhaps other people have said so before, but not one with such justice. I am happier even than Jane; she only smiles, I laugh." },
    // 3 Romeo and Juliet
    { book_id: 3, popularity: 4158, quote: "These violent delights have violent ends\nAnd in their triumph die, like fire and powder,\nWhich as they kiss consume." },
    { book_id: 3, popularity: 3390, quote: "My bounty is as boundless as the sea,\nMy love as deep; the more I give to thee,\nThe more I have, for both are infinite." },
    { book_id: 3, popularity: 2466, quote: "Don't waste your love on somebody, who doesn't value it." },
    { book_id: 3, popularity: 2189, quote: "thus with a kiss I die" },
    { book_id: 3, popularity: 2057, quote: "Good night, good night! parting is such sweet sorrow,\nThat I shall say good night till it be morrow." },
    { book_id: 3, popularity: 1573, quote: "Did my heart love till now? forswear it, sight! For I ne'er saw true beauty till this night." },
    { book_id: 3, popularity: 1388, quote: "For never was a story of more woe than this of Juliet and her Romeo." },
    { book_id: 3, popularity: 1311, quote: "Do not swear by the moon, for she changes constantly, then your love would also change." },
    { book_id: 3, popularity: 1274, quote: "Love is heavy and light, bright and dark, hot and cold, sick and healthy, asleep and awake - its everything except what it is! (Act 1, scene 1)" },
    { book_id: 3, popularity: 843, quote: "What's in a name? That which we call a rose\nBy any other name would smell as sweet." },
    // 4 Little Women
    { book_id: 4, popularity: 3630, quote: "I am not afraid of storms, for I am learning how to sail my ship." },
    { book_id: 4, popularity: 3581, quote: "I like good strong words that mean something…" },
    { book_id: 4, popularity: 1571, quote: "I'd rather take coffee than compliments just now." },
    { book_id: 4, popularity: 1503, quote: "There are many Beths in the world, shy and quiet, sitting in corners till needed, and living for others so cheerfully that no one sees the sacrifices till the little cricket on the hearth stops chirping, and the sweet, sunshiny presence vanishes, leaving silence and shadow behind." },
    { book_id: 4, popularity: 1192, quote: "I've got the key to my castle in the air, but whether I can unlock the door remains to be seen." },
    { book_id: 4, popularity: 1083, quote: "Love Jo all your days, if you choose, but don't let it spoil you, for it's wicked to throw away so many good gifts because you can't have the one you want." },
    { book_id: 4, popularity: 919, quote: "Your father, Jo. He never loses patience, never doubts or complains, but always hopes, and works and waits so cheerfully that one is ashamed to do otherwise before him." },
    { book_id: 4, popularity: 903, quote: "I want to do something splendid...something heroic or wonderful that won't be forgotten after I'm dead. I don't know what, but I'm on the watch for it and mean to astonish you all someday." },
    { book_id: 4, popularity: 899, quote: "Don't laugh at the spinsters, dear girls, for often very tender, tragic romances are hidden away in the hearts that beat so quietly under the sober gowns, and many silent sacrifices of youth, health, ambition, love itself, make the faded faces beautiful in God's sight. Even the sad, sour sisters should be kindly dealt with, because they have missed the sweetest part of life, if for no other reason." },
    { book_id: 4, popularity: 872, quote: "Women, they have minds, and they have souls, as well as just hearts. And they've got ambition, and they've got talent, as well as just beauty. I'm so sick of people saying that love is all a woman is fit for." },
    // 5 Jane Eyre
    { book_id: 5, popularity: 13701, quote: "I am no bird; and no net ensnares me: I am a free human being with an independent will." },
    { book_id: 5, popularity: 10568, quote: "I would always rather be happy than dignified." },
    { book_id: 5, popularity: 5447, quote: "Do you think I am an automaton? — a machine without feelings? and can bear to have my morsel of bread snatched from my lips, and my drop of living water dashed from my cup? Do you think, because I am poor, obscure, plain, and little, I am soulless and heartless? You think wrong! — I have as much soul as you — and full as much heart! And if God had gifted you with some beauty and much wealth, I should have made it as hard for you to leave me, as it is now for me to leave you. I am not talking to you now through the medium of custom, conventionalities, nor even of mortal flesh: it is my spirit that addresses your spirit; just as if both had passed through the grave, and we stood at God's feet, equal — as we are!" },
    { book_id: 5, popularity: 4856, quote: "I care for myself. The more solitary, the more friendless, the more unsustained I am, the more I will respect myself." },
    { book_id: 5, popularity: 4116, quote: "Life appears to me too short to be spent in nursing animosity or registering wrongs." },
    { book_id: 5, popularity: 3329, quote: "I do not think, sir, you have any right to command me, merely because you are older than I, or because you have seen more of the world than I have; your claim to superiority depends on the use you have made of your time and experience." },
    { book_id: 5, popularity: 2984, quote: "I have for the first time found what I can truly love—I have found you. You are my sympathy—my better self—my good angel—I am bound to you with a strong attachment. I think you good, gifted, lovely: a fervent, a solemn passion is conceived in my heart; it leans to you, draws you to my centre and spring of life, wraps my existence about you—and, kindling in pure, powerful flame, fuses you and me in one." },
    { book_id: 5, popularity: 2924, quote: "'No sight so sad as that of a naughty child,' he began, 'especially a naughty little girl. Do you know where the wicked go after death?\n\n'They go to hell,' was my ready and orthodox answer.\n\n'And what is hell? Can you tell me that?'\n\n'A pit full of fire.'\n\n'And should you like to fall into that pit, and to be burning there for ever?'\n\n'No, sir.'\n\n'What must you do to avoid it?'\n\nI deliberated a moment: my answer, when it did come was objectionable: 'I must keep in good health and not die.'\n\n'Children, hell, humor, religion'" },
    { book_id: 5, popularity: 2806, quote: "If all the world hated you and believed you wicked, while your own conscience approved of you and absolved you from guilt, you would not be without friends." },
    // 6 Wuthering Heights
    { book_id: 6, popularity: 12341, quote: "He's more myself than I am. Whatever our souls are made of, his and mine are the same." },
    { book_id: 6, popularity: 7613, quote: "If all else perished, and he remained, I should still continue to be; and if all else remained, and he were annihilated, the universe would turn to a mighty stranger." },
    { book_id: 6, popularity: 4260, quote: "Be with me always – take any form – drive me mad! only do not leave me in this abyss, where I cannot find you! Oh, God! it is unutterable! I cannot live without my life! I cannot live without my soul!" },
    { book_id: 6, popularity: 3386, quote: "I wish I were a girl again, half-savage and hardy, and free." },
    { book_id: 6, popularity: 2846, quote: "Catherine Earnshaw, may you not rest as long as I am living. You said I killed you – haunt me then. The murdered do haunt their murderers. I believe—I know that ghosts have wandered on the earth. Be with me always—take any form—drive me mad! Only do not leave me in this abyss, where I cannot find you! Oh, God! It is unutterable! I cannot live without my life! I cannot live without my soul!" },
    { book_id: 6, popularity: 2570, quote: "If he loved with all the powers of his puny being, he couldn't love as much in eighty years as I could in a day." },
    { book_id: 6, popularity: 2404, quote: "I have not broken your heart - you have broken it; and in breaking it, you have broken mine." },
    { book_id: 6, popularity: 2101, quote: "She burned too bright for this world." },
    { book_id: 6, popularity: 2037, quote: "Terror made me cruel..." },
    { book_id: 6, popularity: 1782, quote: "I cannot express it; but surely you and everybody have a notion that there is or should be an existence of yours beyond you. What were the use of my creation, if I were entirely contained here? My great miseries in this world have been Heathcliff's miseries, and I watched and felt each from the beginning: my great thought in living is himself. If all else perished, and he remained, I should still continue to be; and if all else remained, and he were annihilated, the universe would turn to a mighty stranger..." },
    //7 Frankenstein
    { book_id: 7, popularity: 5218, quote: "Nothing is so painful to the human mind as a great and sudden change." },
    { book_id: 7, popularity: 4966, quote: "Beware; for I am fearless, and therefore powerful." },
    { book_id: 7, popularity: 1800, quote: "Life, although it may only be an accumulation of anguish, is dear to me, and I will defend it." },
    { book_id: 7, popularity: 1394, quote: "I do know that for the sympathy of one living being, I would make peace with all. I have love in me the likes of which you can scarcely imagine and rage the likes of which you would not believe. If I cannot satisfy the one, I will indulge the other." },
    { book_id: 7, popularity: 1162, quote: "There is something at work in my soul, which I do not understand." },
    { book_id: 7, popularity: 1073, quote: "If I cannot inspire love, I will cause fear!" },
    { book_id: 7, popularity: 766, quote: "I ought to be thy Adam, but I am rather the fallen angel..." },
    { book_id: 7, popularity: 704, quote: "Even broken in spirit as he is, no one can feel more deeply than he does the beauties of nature..." },
    { book_id: 7, popularity: 625, quote: "There is love in me the likes of which you've never seen. There is rage in me the likes of which should never escape. If I am not satisfied in the one, I will indulge the other." },
    { book_id: 7, popularity: 579, quote: "...the companions of our childhood always possess a certain power over our minds which hardly any later friend can obtain." },
    //8 dorianGrayQuotes 
    { book_id: 8, popularity: 19806, quote: "The books that the world calls immoral are books that show the world its own shame." },
    { book_id: 8, popularity: 10696, quote: "You will always be fond of me. I represent to you all the sins you never had the courage to commit." },
    { book_id: 8, popularity: 8573, quote: "Experience is merely the name men gave to their mistakes." },
    { book_id: 8, popularity: 7333, quote: "Those who find ugly meanings in beautiful things are corrupt without being charming... There is no such thing as a moral or an immoral book. Books are well written, or badly written. That is all." },
    { book_id: 8, popularity: 5809, quote: "To define is to limit." },
    { book_id: 8, popularity: 5199, quote: "Nowadays people know the price of everything and the value of nothing." },
    { book_id: 8, popularity: 4997, quote: "I don't want to be at the mercy of my emotions. I want to use them, to enjoy them, and to dominate them." },
    { book_id: 8, popularity: 3840, quote: "Behind every exquisite thing that existed, there was something tragic." },
    { book_id: 8, popularity: 3809, quote: "The only way to get rid of temptation is to yield to it." },
    { book_id: 8, popularity: 3745, quote: "I am too fond of reading books to care to write them." },
    //9 huckleberryFinn
    { book_id: 9, popularity: 671, quote: "All right, then, I'll go to hell." },
    { book_id: 9, popularity: 313, quote: "That is just the way with some people. They get down on a thing when they don’t know nothing about it." },
    { book_id: 9, popularity: 284, quote: "Human beings can be awful cruel to one another." },
    { book_id: 9, popularity: 194, quote: "Right is right, and wrong is wrong, and a body ain’t got no business doing wrong when he ain’t ignorant and knows better." },
    { book_id: 9, popularity: 192, quote: "Jim said that bees won't sting idiots, but I didn't believe that, because I tried them lots of times myself and they wouldn't sting me." },
    { book_id: 9, popularity: 156, quote: "I couldn't bear to think about it; and yet, somehow, I couldn't think about nothing else." },
    { book_id: 9, popularity: 153, quote: "I do not wish any reward but to know I have done the right thing." },
    { book_id: 9, popularity: 141, quote: "If you tell the truth you do not need a good memory!" },
    { book_id: 9, popularity: 115, quote: "Hain't we got all the fools in town on our side? And hain't that a big enough majority in any town?" },
    //10 dracula
    { book_id: 10, popularity: 2706, quote: "We learn from failure, not from success!" },
    { book_id: 10, popularity: 1014, quote: "I am longing to be with you, and by the sea, where we can talk together freely and build our castles in the air." },
    { book_id: 10, popularity: 880, quote: "Once again...welcome to my house. Come freely. Go safely; and leave something of the happiness you bring." },
    { book_id: 10, popularity: 817, quote: "I am all in a sea of wonders. I doubt; I fear; I think strange things, which I dare not confess to my own soul." },
    { book_id: 10, popularity: 656, quote: "There is a reason why all things are as they are." },
    { book_id: 10, popularity: 628, quote: "Remember my friend, that knowledge is stronger than memory, and we should not trust the weaker." },
    { book_id: 10, popularity: 485, quote: "I want you to believe...to believe in things that you cannot." },
    { book_id: 10, popularity: 447, quote: "Despair has its own calms." },
    { book_id: 10, popularity: 431, quote: "Loneliness will sit over our roofs with brooding wings." },
    { book_id: 10, popularity: 413, quote: "Oh, the terrible struggle that I have had against sleep so often of late; the pain of the sleeplessness, or the pain of the fear of sleep, and with such unknown horror as it has for me! How blessed are some people, whose lives have no fears, no dreads; to whom sleep is a blessing that comes nightly, and brings nothing but sweet dreams." },
    //11 The Odyssey
    { book_id: 11, popularity: 1204, quote: "Of all creatures that breathe and move upon the earth, nothing is bred that is weaker than man." },
    { book_id: 11, popularity: 624, quote: "There is a time for many words, and there is also a time for sleep." },
    { book_id: 11, popularity: 569, quote: "There is nothing more admirable than when two people who see eye to eye keep house as man and wife, confounding their enemies and delighting their friends." },
    { book_id: 11, popularity: 560, quote: "A man who has been through bitter experiences and travelled far enjoys even his sufferings after a time." },
    { book_id: 11, popularity: 514, quote: "'Be strong, saith my heart; I am a soldier, I have seen worse sights than this.'" },
    { book_id: 11, popularity: 476, quote: "For a friend with an understanding heart is worth no less than a brother." },
    { book_id: 11, popularity: 290, quote: "Men are so quick to blame the gods: they say that we devise their misery. But they themselves - in their depravity - design grief greater than the griefs that fate assigns." },
    { book_id: 11, popularity: 268, quote: "Sleep, delicious and profound, the very counterfeit of death." },
    { book_id: 11, popularity: 219, quote: "'My name is Nobody.'" },
    { book_id: 11, popularity: 214, quote: "Ah how shameless – the way these mortals blame the gods. From us alone they say come all their miseries but they themselves with their own reckless ways compound their pains beyond their proper share." },
    //12 anne Of Green Gables
    { book_id: 12, popularity: 4368, quote: "I'm so glad I live in a world where there are Octobers." },
    { book_id: 12, popularity: 4064, quote: "It's been my experience that you can nearly always enjoy things if you make up your mind firmly that you will." },
    { book_id: 12, popularity: 3577, quote: "Kindred spirits are not so scarce as I used to think. It's splendid to find out there are so many of them in the world." },
    { book_id: 12, popularity: 2492, quote: "True friends are always together in spirit." },
    { book_id: 12, popularity: 2398, quote: "My life is a perfect graveyard of buried hopes." },
    { book_id: 12, popularity: 2004, quote: "Life is worth living as long as there's a laugh in it." },
    { book_id: 12, popularity: 1742, quote: "'Dear old world,' she murmured, 'you are very lovely, and I am glad to be alive in you.'" },
    { book_id: 12, popularity: 1432, quote: "People laugh at me because I use big words. But if you have big ideas, you have to use big words to express them, haven't you?" },
    { book_id: 12, popularity: 1235, quote: "There's such a lot of different Annes in me. I sometimes think that is why I'm such a troublesome person." },
    { book_id: 12, popularity: 1064, quote: "Because when you are imagining, you might as well imagine something worth while." },
    { book_id: 12, popularity: 1032, quote: "Oh, it's delightful to have ambitions. I'm so glad I have such a lot." },
    { book_id: 12, popularity: 971, quote: "Why must people kneel down to pray? If I really wanted to pray, I'd tell you what I'd do." },
    { book_id: 12, popularity: 962, quote: "It was November—the month of crimson sunsets, parting birds, deep, sad hymns of the sea." },
    { book_id: 12, popularity: 792, quote: "Tomorrow is a new day with no mistakes in it... yet." },
    { book_id: 12, popularity: 787, quote: "Look at that sea, girls—all silver and shadow and vision of things not seen." },
    //13  taleOfTwoCitiesQuotes = [
    { book_id: 13, popularity: 3140, quote: "A wonderful fact to reflect upon, that every human creature is constituted to be that profound secret and mystery to every other." },
    { book_id: 13, popularity: 3009, quote: "It is a far, far better thing that I do, than I have ever done; it is a far, far better rest that I go to than I have ever known." },
    { book_id: 13, popularity: 2405, quote: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness..." },
    { book_id: 13, popularity: 1609, quote: "You have been the last dream of my soul." },
    { book_id: 13, popularity: 1383, quote: "It was the best of times, it was the worst of times." },
    { book_id: 13, popularity: 1275, quote: "I wish you to know that you have been the last dream of my soul." },
    { book_id: 13, popularity: 884, quote: "And yet I have had the weakness, and have still the weakness, to wish you to know with what a sudden mastery you kindled me, heap of ashes that I am, into fire." },
    { book_id: 13, popularity: 673, quote: "I see a beautiful city and a brilliant people rising from this abyss..." },
    { book_id: 13, popularity: 552, quote: "A day wasted on others is not wasted on one's self." },
    { book_id: 13, popularity: 477, quote: "There is prodigious strength in sorrow and despair." },
    { book_id: 13, popularity: 460, quote: "Think now and then that there is a man who would give his life, to keep a life you love beside you." },
    { book_id: 13, popularity: 437, quote: "'Before I go,' he said, and paused — 'May I kiss her?'" },
    //14 monte Cristo 
    { book_id: 14, popularity: 2944, quote: "I am not proud, but I am happy; and happiness blinds, I think, more than pride." },
    { book_id: 14, popularity: 2773, quote: "All human wisdom is contained in these two words - Wait and Hope." },
    { book_id: 14, popularity: 1295, quote: "Life is a storm, my young friend. You will bask in the sunlight one moment, be shattered on the rocks the next. What makes you a man is what you do when that storm comes." },
    { book_id: 14, popularity: 1247, quote: "It's necessary to have wished for death in order to know how good it is to live." },
    { book_id: 14, popularity: 1124, quote: "Woman is sacred; the woman one loves is holy." },
    { book_id: 14, popularity: 1025, quote: "The difference between treason and patriotism is only a matter of dates." },
    { book_id: 14, popularity: 1014, quote: "Moral wounds have this peculiarity - they may be hidden, but they never close; always painful, always ready to bleed when touched." },
    { book_id: 14, popularity: 973, quote: "When you compare the sorrows of real life to the pleasures of the imaginary one, you will never want to live again, only to dream forever." },
    { book_id: 14, popularity: 954, quote: "How did I escape? With difficulty. How did I plan this moment? With pleasure." },
    { book_id: 14, popularity: 909, quote: "Learning does not make one learned: there are those who have knowledge and those who have understanding." },
    { book_id: 14, popularity: 768, quote: "For all evils there are two remedies - time and silence." },
    { book_id: 14, popularity: 558, quote: "There are two ways of seeing: with the body and with the soul. The body's sight can sometimes forget, but the soul remembers forever." },
    { book_id: 14, popularity: 491, quote: "I have always had more dread of a pen, a bottle of ink, and a sheet of paper than of a sword or pistol." },
    { book_id: 14, popularity: 490, quote: "We are always in a hurry to be happy; for when we have suffered a long time, we have great difficulty in believing in good fortune." },
    { book_id: 14, popularity: 408, quote: "I don't think man was meant to attain happiness so easily. Happiness is like those palaces in fairy tales whose gates are guarded by dragons: we must fight in order to conquer it." },
    //15 monte Cristo 
    { book_id: 15, popularity: 8578, quote: "Pain and suffering are always inevitable for a large intelligence and a deep heart. The really great men must, I think, have great sadness on earth." },
    { book_id: 15, popularity: 6314, quote: "To go wrong in one's own way is better than to go right in someone else's." },
    { book_id: 15, popularity: 2783, quote: "We sometimes encounter people, even perfect strangers, who begin to interest us at first sight, somehow suddenly, all at once, before a word has been spoken." },
    { book_id: 15, popularity: 2773, quote: "It takes something more than intelligence to act intelligently." },
    { book_id: 15, popularity: 2154, quote: "Taking a new step, uttering a new word, is what people fear most." },
    { book_id: 15, popularity: 1455, quote: "Your worst sin is that you have destroyed and betrayed yourself for nothing." },
    { book_id: 15, popularity: 1155, quote: "Pain and suffering are always inevitable for a large intelligence and a deep heart." },
    { book_id: 15, popularity: 1014, quote: "I used to analyze myself down to the last thread, used to compare myself with others, recalled all the smallest glances, smiles and words of those to whom I’d tried to be frank." },
    { book_id: 15, popularity: 819, quote: "When reason fails, the devil helps!" },
    { book_id: 15, popularity: 802, quote: "I did not bow down to you, I bowed down to all the suffering of humanity." },
    { book_id: 15, popularity: 784, quote: "The man who has a conscience suffers whilst acknowledging his sin. That is his punishment." },
    { book_id: 15, popularity: 668, quote: "We're always thinking of eternity as an idea that cannot be understood, something immense. But why must it be?" },
    { book_id: 15, popularity: 549, quote: "And the more I drink the more I feel it. That's why I drink too. I try to find sympathy and feeling in drink… I drink so that I may suffer twice as much!" },
    { book_id: 15, popularity: 518, quote: "Power is given only to him who dares to stoop and take it… one must have the courage to dare." },
    //16 monte Cristo 
    { book_id: 16, popularity: 3351, quote: "If I loved you less, I might be able to talk about it more." },
    { book_id: 16, popularity: 2454, quote: "Silly things do cease to be silly if they are done by sensible people in an impudent way." },
    { book_id: 16, popularity: 2147, quote: "I may have lost my heart, but not my self-control." },
    { book_id: 16, popularity: 1945, quote: "I cannot make speeches, Emma...If I loved you less, I might be able to talk about it more." },
    { book_id: 16, popularity: 1684, quote: "I always deserve the best treatment because I never put up with any other." },
    { book_id: 16, popularity: 1145, quote: "Seldom, very seldom, does complete truth belong to any human disclosure; seldom can it happen that something is not a little disguised or a little mistaken." },
    { book_id: 16, popularity: 810, quote: "There are people, who the more you do for them, the less they will do for themselves." },
    { book_id: 16, popularity: 719, quote: "One half of the world cannot understand the pleasures of the other." },
    { book_id: 16, popularity: 639, quote: "You must be the best judge of your own happiness." },
    { book_id: 16, popularity: 631, quote: "Without music, life would be a blank to me." },
    { book_id: 16, popularity: 576, quote: "Better be without sense than misapply it as you do." },
    { book_id: 16, popularity: 392, quote: "Were I to fall in love, indeed, it would be a different thing; but I have never been in love; it is not my way, or my nature; and I do not think I ever shall." },
    { book_id: 16, popularity: 378, quote: "Men of sense, whatever you may choose to say, do not want silly wives." },
    { book_id: 16, popularity: 297, quote: "Indeed, I am very sorry to be right in this instance. I would much rather have been merry than wise." },
    { book_id: 16, popularity: 293, quote: "She was one of those, who, having once begun, would be always in love." },
    { book_id: 16, popularity: 286, quote: "I lay it down as a general rule, Harriet, that if a woman doubts as to whether she should accept a man or not, she certainly ought to refuse him." },
    { book_id: 16, popularity: 263, quote: "Vanity working on a weak head produces every sort of mischief." },
    //17 anna Karenina
    { book_id: 17, popularity: 7892, quote: "All happy families are alike; each unhappy family is unhappy in its own way." },
    { book_id: 17, popularity: 5697, quote: "If you look for perfection, you'll never be content." },
    { book_id: 17, popularity: 5585, quote: "I think... if it is true that there are as many minds as there are heads, then there are as many kinds of love as there are hearts." },
    { book_id: 17, popularity: 4003, quote: "He stepped down, trying not to look long at her, as if she were the sun, yet he saw her, like the sun, even without looking." },
    { book_id: 17, popularity: 3630, quote: "Respect was invented to cover the empty place where love should be." },
    { book_id: 17, popularity: 2443, quote: "Spring is the time of plans and projects." },
    { book_id: 17, popularity: 2238, quote: "Is it really possible to tell someone else what one feels?" },
    { book_id: 17, popularity: 1800, quote: "Rummaging in our souls, we often dig up something that ought to have lain there unnoticed." },
    { book_id: 17, popularity: 1615, quote: "I've always loved you, and when you love someone, you love the whole person, just as he or she is, and not as you would like them to be." },
    { book_id: 17, popularity: 1440, quote: "Be bad, but at least don't be a liar, a deceiver!" },
    { book_id: 17, popularity: 1437, quote: "Love. The reason I dislike that word is that it means too much for me, far more than you can understand." },
    { book_id: 17, popularity: 1366, quote: "All the variety, all the charm, all the beauty of life is made up of light and shadow." },
    { book_id: 17, popularity: 1129, quote: "Anything is better than lies and deceit!" },
    { book_id: 17, popularity: 957, quote: "I always loved you, and if one loves anyone, one loves the whole person, just as they are and not as one would like them to be." },
    { book_id: 17, popularity: 840, quote: "Sometimes she did not know what she feared, what she desired: whether she feared or desired what had been or what would be, and precisely what she desired, she did not know." },
    { book_id: 17, popularity: 829, quote: "All the girls in the world were divided into two classes: one class included all the girls in the world except her, and they had all the usual human feelings and were very ordinary girls; while the other class - herself alone - had no weaknesses and was superior to all humanity." },
    //18 lesMiserables
    { book_id: 18, popularity: 1228, quote: "Promise to give me a kiss on my brow when I am dead. --I shall feel it." },
    { book_id: 18, popularity: 1081, quote: "If I speak, I am condemned. If I stay silent, I am damned!" },
    { book_id: 18, popularity: 1001, quote: "You who suffer because you love, love still more. To die of love is to live by it." },
    { book_id: 18, popularity: 972, quote: "Teach the ignorant as much as you can; society is culpable in not providing a free education for all and it must answer for the night which it produces." },
    { book_id: 18, popularity: 963, quote: "You ask me what forces me to speak? A strange thing: my conscience." },
    { book_id: 18, popularity: 897, quote: "A garden to walk in and immensity to dream in--what more could he ask? A few flowers at his feet and above him the stars." },
    { book_id: 18, popularity: 801, quote: "There is nothing like a dream to create the future." },
    { book_id: 18, popularity: 791, quote: "A man is not idle because he is absorbed in thought. There is visible labor and there is invisible labor." },
    { book_id: 18, popularity: 769, quote: "Life's great happiness is to be convinced we are loved." },
    { book_id: 18, popularity: 720, quote: "He was fond of books, for they are cool and sure friends." },
    { book_id: 18, popularity: 617, quote: "The pupil dilates in darkness and in the end finds light, just as the soul dilates in misfortune and in the end finds God." },
    { book_id: 18, popularity: 611, quote: "The future has several names. For the weak, it is impossible; for the fainthearted, it is unknown; but for the valiant, it is ideal." },
    { book_id: 18, popularity: 597, quote: "There is always more misery among the lower classes than there is humanity in the higher." },
    { book_id: 18, popularity: 578, quote: "When love has fused and mingled two beings in a sacred and angelic unity, the secret of life has been discovered so far as they are concerned." },
    //19 alices
    { book_id: 19, popularity: 1104, quote: "If you drink much from a bottle marked 'poison' it is certain to disagree with you sooner or later." },
    { book_id: 19, popularity: 544, quote: "How puzzling all these changes are! I'm never sure what I'm going to be, from one minute to another." },
    { book_id: 19, popularity: 456, quote: "'And what is the use of a book,' thought Alice, 'without pictures or conversation?'" },
    { book_id: 19, popularity: 332, quote: "'Then,' said the cat, 'it really doesn’t matter, does it?'" },
    { book_id: 19, popularity: 291, quote: "In another moment down went Alice after it, never once considering how in the world she was to get out again." },
    { book_id: 19, popularity: 178, quote: "'That's the reason they're called lessons,' the Gryphon remarked: 'because they lessen from day to day." },
    { book_id: 19, popularity: 161, quote: "'How long is forever?' 'Sometimes just one second.'" },
    { book_id: 19, popularity: 105, quote: "Alice thought to herself 'I don't see how he can ever finish, if he doesn't begin.'" },
    { book_id: 19, popularity: 89, quote: "Alice had begun to think that very few things indeed were really impossible." },
    { book_id: 19, popularity: 72, quote: "I almost wish I hadn't gone down that rabbit-hole—and yet—and yet—it's rather curious, you know, this sort of life!" },
    { book_id: 19, popularity: 64, quote: "At any rate, there's no harm in trying." },
    { book_id: 19, popularity: 62, quote: "'I—I hardly know, sir, just at present—at least I know who I WAS when I got up this morning, but I think I must have been changed several times since then.'" },
    { book_id: 19, popularity: 46, quote: "A dream is not reality but who's to say which is which?" },
    { book_id: 19, popularity: 42, quote: "'Dear, dear! How queer everything is to-day!'" },
    { book_id: 19, popularity: 41, quote: "'If you knew Time as well as I do,' said the Hatter, 'you wouldn’t talk about wasting it. It’s him.'" },
    //20 moby dick
    { book_id: 20, popularity: 2646, quote: "I know not all that may be coming, but be it what it will, I'll go to it laughing." },
    { book_id: 20, popularity: 904, quote: "It is not down on any map; true places never are." },
    { book_id: 20, popularity: 820, quote: "Better to sleep with a sober cannibal than a drunk Christian." },
    { book_id: 20, popularity: 788, quote: "As for me, I am tormented with an everlasting itch for things remote. I love to sail forbidden seas, and land on barbarous coasts." },
    { book_id: 20, popularity: 685, quote: "Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses..." },
    { book_id: 20, popularity: 626, quote: "There are certain queer times and occasions in this strange mixed affair we call life when a man takes this whole universe for a vast practical joke..." },
    { book_id: 20, popularity: 518, quote: "I try all things, I achieve what I can." },
    { book_id: 20, popularity: 467, quote: "Ignorance is the parent of fear." },
    //21 art Of War
    { book_id: 21, popularity: 3822, quote: "Appear weak when you are strong, and strong when you are weak." },
    { book_id: 21, popularity: 2977, quote: "The supreme art of war is to subdue the enemy without fighting." },
    { book_id: 21, popularity: 2386, quote: "If you know the enemy and know yourself, you need not fear the result of a hundred battles." },
    { book_id: 21, popularity: 1887, quote: "Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt." },
    { book_id: 21, popularity: 1397, quote: "In the midst of chaos, there is also opportunity." },
    { book_id: 21, popularity: 1324, quote: "Supreme excellence consists of breaking the enemy's resistance without fighting." },
    { book_id: 21, popularity: 1319, quote: "All warfare is based on deception." },
    { book_id: 21, popularity: 1211, quote: "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win." },
    { book_id: 21, popularity: 959, quote: "The greatest victory is that which requires no battle." },
    { book_id: 21, popularity: 929, quote: "If your enemy is secure at all points, be prepared for him. If he is in superior strength, evade him." },
    { book_id: 21, popularity: 711, quote: "Engage people with what they expect; it is what they are able to discern and confirms their projections." },
    { book_id: 21, popularity: 710, quote: "There is no instance of a nation benefitting from prolonged warfare." },
    { book_id: 21, popularity: 634, quote: "Treat your men as you would your own beloved sons. And they will follow you into the deepest valley." },
    { book_id: 21, popularity: 632, quote: "Thus we may know that there are five essentials for victory." },
    //22  wizard Of Oz
    { book_id: 22, popularity: 3, quote: "East, west - home's best!" },
    { book_id: 22, popularity: 3, quote: "She bade her friends good-bye, and again started along the road of yellow brick. When she had gone several miles she thought she would stop to rest, and so climbed to the top of the fence beside the road and sat down." },
    { book_id: 22, popularity: 3, quote: "'You people with hearts,' he said, 'have something to guide you, and need never do wrong; but I have no heart, and so I must be very careful.'" },
    { book_id: 22, popularity: 3, quote: "I have always thought myself very big and terrible; yet such small things as flowers came near to killing me, and such small animals as mice have saved my life. How strange it all is!" },
    { book_id: 22, popularity: 3, quote: "All you need is confidence in yourself. There is no living thing that is not afraid when it faces danger. True courage is in facing danger when you are afraid." },
    { book_id: 22, popularity: 3, quote: "A baby has brains, but it doesn’t know much. Experience is the only thing that brings knowledge, and the longer you are on earth the more experience you are sure to get." },
    { book_id: 22, popularity: 3, quote: "'Which road leads to the Wicked Witch of the West?' asked Dorothy. 'There is no road,' answered the Guardian of the Gates. 'No one ever wishes to go that way.'" },
    { book_id: 22, popularity: 3, quote: "'Have you brains?' Asked the Scarecrow. 'I suppose. I've never looked to see.' Replied the Lion." },
    { book_id: 22, popularity: 3, quote: "'Well,' said the Cowardly Lion, drawing a long breath of relief, 'I see we are going to live a little while longer, and I am glad of it, for it must be a very uncomfortable thing not to be alive.'" },
    //23 iliad
    { book_id: 23, popularity: 1165, quote: "...There is the heat of Love, the pulsing rush of Longing, the lover’s whisper, irresistible—magic to make the sanest man go mad." },
    { book_id: 23, popularity: 883, quote: "Hateful to me as the gates of Hades is that man who hides one thing in his heart and speaks another." },
    { book_id: 23, popularity: 510, quote: "Let me not then die ingloriously and without a struggle, but let me first do some great thing that shall be told among men hereafter." },
    { book_id: 23, popularity: 385, quote: "Sing, O muse, of the rage of Achilles, son of Peleus, that brought countless ills upon the Achaeans." },
    { book_id: 23, popularity: 371, quote: "Like the generations of leaves, the lives of mortal men. Now the wind scatters the old leaves across the earth, now the living timber bursts with the new buds..." },
    { book_id: 23, popularity: 355, quote: "We men are wretched things." },
    { book_id: 23, popularity: 327, quote: "Why so much grief for me? No man will hurl me down to Death, against my fate." },
    { book_id: 23, popularity: 273, quote: "Achilles glared at him and answered, 'Fool, prate not to me about covenants. There can be no covenants between men and lions...'" },
    { book_id: 23, popularity: 191, quote: "...like that star of the waning summer who beyond all stars rises bathed in the ocean stream to glitter in brilliance." },
    { book_id: 23, popularity: 173, quote: "No one can hurry me down to Hades before my time, but if a man's hour is come, be he brave or be he coward, there is no escape for him when he has once been born." },
    { book_id: 23, popularity: 167, quote: "No man or woman born, coward or brave, can shun his destiny." },
    { book_id: 23, popularity: 165, quote: "His descent was like nightfall." },
    { book_id: 23, popularity: 164, quote: "Come, Friend, you too must die. Why moan about it so? Even Patroclus died, a far, far better man than you." },
    //24 Sherlock Holmes
    { book_id: 24, popularity: 750, quote: "Life is infinitely stranger than anything which the mind of man could invent. We would not dare to conceive the things which are really mere commonplaces of existence." },
    { book_id: 24, popularity: 500, quote: "Women are naturally secretive, and they like to do their own secreting." },
    { book_id: 24, popularity: 237, quote: "Never trust to general impressions, my boy, but concentrate yourself upon details." },
    { book_id: 24, popularity: 213, quote: "As a rule, the more bizarre a thing is the less mysterious it proves to be." },
    { book_id: 24, popularity: 146, quote: "'Come, Watson, come!' he cried. 'The game is afoot.'" },
    { book_id: 24, popularity: 138, quote: "To Sherlock Holmes she is always the woman. I have seldom heard him mention her under any other name." },
    { book_id: 24, popularity: 129, quote: "Violence does, in truth, recoil upon the violent, and the schemer falls into the pit which he digs for another." },
    { book_id: 24, popularity: 87, quote: "It is a capital mistake to theorise before one has data." },
    { book_id: 24, popularity: 86, quote: "Circumstantial evidence is a very tricky thing." },
    { book_id: 24, popularity: 68, quote: "'The future was with Fate. The present was our own.' - The Poison Belt" },
    { book_id: 24, popularity: 68, quote: "A sandwich and a cup of coffee, and then off to violin-land, where all is sweetness and delicacy and harmony." },
    { book_id: 24, popularity: 61, quote: "When a doctor does go wrong he is the first of criminals." },
    { book_id: 24, popularity: 60, quote: "It's a wicked world, and when a clever man turns his brain to crime it is the worst of all." }
];

export { authors, books, quotes };