name: Quarter Hourly Cron Job

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:       # Optional: allows manual triggering

jobs:
  visit-url:
    runs-on: ubuntu-latest

    steps:
      - name: Call the URL with authentication
        run: |
          echo "Calling endpoint at $(date)"
          curl -v -H "Authorization: Bearer ${{ secrets.MY_SECRET_TOKEN }}" https://app.publicdomainlibrary.org/cron/quarterHourly